swap quotes

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -66,5 +66,7 @@ runs:
       shell: bash -el {0}
       run: snakemake --directory ${{ inputs.directory }} --snakefile ${{ inputs.snakefile }} --show-failed-logs ${{ inputs.args }} --containerize > Dockerfile
     - if: ${{ ! (inputs.task == 'containerize' || inputs.task == 'run' )}}
-      run: echo "Invalid value for 'task': '${{ inputs.task }}'. Options: 'containerize', 'run'." && exit 1
+      run: |
+        echo 'Invalid value for "task": "${{ inputs.task }}". Options: "containerize", "run".'
+        exit 1
 
