move check for containerize/run to top

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -38,6 +38,12 @@ inputs:
 runs:
   using: 'composite'
   steps:
+    - name: Validate inputs
+      if: ${{ ! (inputs.task == 'containerize' || inputs.task == 'run' )}}
+      shell: bash -el {0}
+      run: |
+        echo 'Invalid value for "task": "${{ inputs.task }}". Options: "containerize", "run".'
+        exit 1
     - shell: bash -el {0}
       run: sed 's/{{ snakemake_version }}/${{ inputs.snakemake-version }}/g' environment.yaml.template > environment.yaml
     - name: Setup conda
@@ -65,9 +71,4 @@ runs:
       if: ${{ inputs.task == 'containerize' }}
       shell: bash -el {0}
       run: snakemake --directory ${{ inputs.directory }} --snakefile ${{ inputs.snakefile }} --show-failed-logs ${{ inputs.args }} --containerize > Dockerfile
-    - if: ${{ ! (inputs.task == 'containerize' || inputs.task == 'run' )}}
-      shell: bash -el {0}
-      run: |
-        echo 'Invalid value for "task": "${{ inputs.task }}". Options: "containerize", "run".'
-        exit 1
 
